### ISSUE TITLE
ios：BiometricsScannerSpec/BiometricsScannerSpec.h file not found

### ISSUE THREAD

**Issue by stonehiy** [Francesco-Voto/react-native-biometrics-scanner#6]
ios：BiometricsScannerSpec/BiometricsScannerSpec.h file not found

**Comment by Francesco-Voto** [comment]
can you provide some more info? are you using the new architecture flag enabled?

**Comment by Francesco-Voto** [comment]
@stonehiy the example project is updated now. Please check it now

**Comment by stonehiy** [comment]
> @stonehiy the example project is updated now. Please check it now

Thank you, but my project cannot use the new architecture. I have modified and compatible with the old architecture
