### ISSUE TITLE
Errors thrown are mostly generic

### ISSUE THREAD

**Issue by DJHunn39** [Francesco-Voto/react-native-biometrics-scanner#9]
When functions from this module throw errors, they are mostly generic, as the custom error classes only extend `Error` without any code to set their `name` nor set a typical error message. The simplest way to tell them apart is to use `instanceof`.

Updating these classes to add more info would be useful when handling the various errors that the module throws.

I'm happy to submit a PR for this issue

**Comment by Francesco-Voto** [comment]
Ehy @DJHunn39 feel free to submit a PR.

Anyway I do not understand why put more inside the error it self should be better than goes with `instanceof `. If some situation is missing we can simply add more error classes. Can you provide an example about why this should be better?

**Comment by DJHunn39** [comment]
@Francesco-Voto sure, essentially it's just a bit confusing if an error and you aren't aware of the different error class names - you'd need to go into the source code of this module to try and figure it out, whereas if the error's `name` were set to the name of the class, you could see it in a log really easily:

```
   try {
        const availableBiometric = await getAvailableBiometric(true); // Assuming this errors because the user is not enrolled
        // ... do stuff with availableBiometric
      } catch (e) {
        console.error(e)
      }
```
The console log here is just `[Error]`.

Whereas, with a bit more added to the constructor i.e

```
export class BiometricNoEnrollError extends Error {
  constructor() {
    super('User not enrolled.');
    this.name = 'BiometricNoEnrollError';
  }
}
```

The same snippet from above produces a much more useful console log: `[BiometricNoEnrollError: User not enrolled.]`

**Comment by Francesco-Voto** [comment]
k thanks for raising this up. I can fix this or if you have time feel free to update the code and open a PR

**Comment by DJHunn39** [comment]
@Francesco-Voto just opened a PR ^
